openapi: 3.0.3
info:
  title: 'Laravel API Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
tags:
  -
    name: Endpoints
    description: ''
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/ping:
    get:
      summary: ''
      operationId: getApiPing
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  mensaje: 'API de Laravel funcionando'
                  ok: true
                properties:
                  mensaje:
                    type: string
                    example: 'API de Laravel funcionando'
                  ok:
                    type: boolean
                    example: true
      tags:
        - Endpoints
      security: []
  /api/usuarios/registrar:
    post:
      summary: ''
      operationId: postApiUsuariosRegistrar
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: vmqeopfuudtdsufvyvddq
                apellido1:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: amniihfqcoynlazghdtqt
                apellido2:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: qxbajwbpilpmufinllwlo
                  nullable: true
                correo:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: auydlsmsjuryvojcybzvr
                clave:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: byickznkygloigmkwxphlvazjrcnfbaqywuxhgjjmzuxjubqouzswiwxtrkimfcatbxspzmrazs
                nick:
                  type: string
                  description: 'Must not be greater than 50 characters.'
                  example: royjpxmqesedyghenqcop
              required:
                - nombre
                - apellido1
                - correo
                - clave
                - nick
      security: []
  /api/validar-username:
    post:
      summary: ''
      operationId: postApiValidarUsername
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/validar-email:
    post:
      summary: ''
      operationId: postApiValidarEmail
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/login:
    post:
      summary: ''
      operationId: postApiLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                correo:
                  type: string
                  description: 'Must be a valid email address.'
                  example: qkunze@example.com
                clave:
                  type: string
                  description: ''
                  example: consequatur
              required:
                - correo
                - clave
      security: []
  /api/usuarios/avatares:
    get:
      summary: ''
      operationId: getApiUsuariosAvatares
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example:
                  - avatar-aldeano.png
                  - avatar-bruja.png
                  - avatar-cazador.png
                  - avatar-cupido.png
                  - avatar-ladron.png
                  - avatar-lobo.png
                  - avatar-nina.png
                  - avatar-vidente.png
                  - avatar-oficial.jpg
                  - AVATAR-USUARIO.png
      tags:
        - Endpoints
      security: []
  /api/broadcasting/auth:
    get:
      summary: 'Authenticate the request for channel access.'
      operationId: authenticateTheRequestForChannelAccess
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/me:
    get:
      summary: ''
      operationId: getApiMe
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/logout:
    post:
      summary: ''
      operationId: postApiLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/usuarios:
    get:
      summary: ''
      operationId: getApiUsuarios
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/usuarios/{user_id}':
    get:
      summary: ''
      operationId: getApiUsuariosUser_id
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiUsuariosUser_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: vmqeopfuudtdsufvyvddq
                  nullable: true
                apellido1:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: amniihfqcoynlazghdtqt
                  nullable: true
                apellido2:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: qxbajwbpilpmufinllwlo
                  nullable: true
                nick:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: auydlsmsjuryvojcybzvr
                  nullable: true
                correo:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: byickznkygloigmkwxphl
                  nullable: true
                clave:
                  type: string
                  description: 'Must be at least 6 characters.'
                  example: vazjrcnfbaqywuxhgjjmzuxjubqouzswiwxtrkimfcatbxspzmrazsroyjpxmqesedyghenqco
                  nullable: true
                rol_corp:
                  type: boolean
                  description: ''
                  example: true
                  nullable: true
      security: []
    delete:
      summary: ''
      operationId: deleteApiUsuariosUser_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: user_id
        description: 'The ID of the user.'
        example: 1
        required: true
        schema:
          type: integer
  /api/usuarios-buscar:
    get:
      summary: ''
      operationId: getApiUsuariosBuscar
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/partidas:
    get:
      summary: ''
      operationId: getApiPartidas
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiPartidas
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre_partida:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: vmqeopfuudtdsufvyvddq
              required:
                - nombre_partida
      security: []
  '/api/partidas/{id}':
    get:
      summary: ''
      operationId: getApiPartidasId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the partida.'
        example: consequatur
        required: true
        schema:
          type: string
  '/api/partidas/{id}/unirse':
    post:
      summary: ''
      operationId: postApiPartidasIdUnirse
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the partida.'
        example: consequatur
        required: true
        schema:
          type: string
  '/api/partidas/{id}/salir':
    post:
      summary: ''
      operationId: postApiPartidasIdSalir
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the partida.'
        example: consequatur
        required: true
        schema:
          type: string
  /api/chat/send-private:
    post:
      summary: ''
      operationId: postApiChatSendPrivate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                partida_id:
                  type: integer
                  description: 'The <code>id</code> of an existing record in the partidas table.'
                  example: 17
                contenido:
                  type: string
                  description: 'Must not be greater than 1000 characters.'
                  example: mqeopfuudtdsufvyvddqa
              required:
                - partida_id
                - contenido
      security: []
  '/api/partidas/{id}/iniciar':
    post:
      summary: ''
      operationId: postApiPartidasIdIniciar
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the partida.'
        example: consequatur
        required: true
        schema:
          type: string
  /api/usuarios/actualizar-imagen:
    post:
      summary: ''
      operationId: postApiUsuariosActualizarImagen
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                imagen-perfil:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 4096 kilobytes.'
              required:
                - imagen-perfil
      security: []
  /api/usuarios/elegir-avatar:
    post:
      summary: ''
      operationId: postApiUsuariosElegirAvatar
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  description: ''
                  example: consequatur
              required:
                - avatar
      security: []
  /api/usuario/update:
    put:
      summary: ''
      operationId: putApiUsuarioUpdate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                nick:
                  type: string
                  description: ''
                  example: null
                clave:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: vmqeopfuudtdsufvyvddqamniihfqcoynlazghdtqtqxbajwbpilpmufinllwloauydlsmsjury
      security: []
  /api/users:
    get:
      summary: ''
      operationId: getApiUsers
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
